### PR TITLE
release version 1.0.31: bump libz-rs-sys version

### PR DESCRIPTION
**Pull request by folkertdev**
fixes https://github.com/rust-lang/flate2-rs/issues/413

### CODE REVIEW

**Comment by Byron** [comment]
Thanks a lot!

It looks like Fuzz failure is unrelated and is already [known upstream](https://github.com/google/oss-fuzz/issues/12168). Let's subscribe and check back here once it's fixed or there is a workaround.

**Review by Byron — APPROVED** [review]
LGTM!

**Comment by folkertdev** [comment]
@Byron this was merged but not actually released?

**Comment by Byron** [comment]
Thanks for the heads-up, I have just published the latest version here: https://crates.io/crates/flate2/1.0.31.
A `CHANGELOG.md` will now also be available once #416 was merged.

**Pull request merged**
