### PR TITLE
Update to miniz_oxide 0.5 / quickcheck 1.0 / rand 0.8

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
Windows CI failure seems unrelated

**Comment by sdroege** [comment]
Sure, let's try that

**Comment by sdroege** [comment]
That worked, good idea :)

**Comment by emilk** [comment]
Can we please have a patch release with this change? 🙏

**Comment by alexcrichton** [comment]
Sure, published now

**Pull request merged**
