### PR TITLE
prepare next patch-release

### PR DESCRIPTION
**Pull request by Byron**
A release to incorporate fixes related to uses of uninitialized memory, originally requested [here](https://github.com/rust-lang/flate2-rs/issues/220#issuecomment-1756362420).

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by Byron** [comment]
Thanks you! Could you also merge it? Unfortunately I am not allowed despite it being approved.

**Comment by Manishearth** [comment]
I'm not a libs team member, I don't have merge rights here.

cc @rust-lang/libs

**Comment by joshtriplett** [comment]
@Byron We should fix that and get you the appropriate merge rights.

**Comment by Manishearth** [comment]
Since we're not landing this immediately anyway, perhaps we can land https://github.com/rust-lang/flate2-rs/pull/380 first

**Review by JohnTitor — APPROVED** [review]
The rust-lang/crate-maintainers team has review/merge rights so you can ask them for a review instead of t-libs :)

**Comment by Byron** [comment]
Thank you!

The new release is now available here: https://github.com/rust-lang/flate2-rs/releases/tag/1.0.28 .

**Pull request merged**
