### PR TITLE
Add [De]Compress::new_gzip

### PR DESCRIPTION
**Pull request by coolreader18**
Related to #240

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you be sure to add some tests for this as well? I wasn't aware of this feature of adding 16 to zlib window bits (I still don't know what those are...)

**Comment by coolreader18** [comment]
Yeah, I don't really know either :sweat_smile: . I added a test just round-tripping through new_gzip Compress/Decompress, hopefully that's good.

**Comment by coolreader18** [comment]
Would you be able to cut a new release for crates.io? Or are there generally more changes in a given release?

**Comment by alexcrichton** [comment]
Sure thing, published now.

**Pull request merged**
