### PR TITLE
prepare 1.0.27 release

### PR DESCRIPTION
**Pull request by Byron**
This release contains improved documentation and a few API improvements.

### CODE REVIEW

**Comment by jongiddy** [comment]
@Byron Thank you for all the effort you have put in to clearing over 9 months of PR backlog. I very much approve this release!

**Review by JohnTitor — APPROVED** [review]
🚀 Thanks!

**Comment by Byron** [comment]
Thanks :)!

I just realized that I am not a crate owner here and thus can't perform the publish. Also CC @joshtriplett in case this isn't intended.

In the meantime, I'd appreciate if somebody with permissions can perform the release to crates.io. Thanks again.

**Comment by jongiddy** [comment]
Does the publish process create the tag or does that need to be done as an additional step?

**Comment by Byron** [comment]
It's an additional step. The whole process is also [outlined in the maintenance document](https://github.com/rust-lang/flate2-rs/blob/main/MAINTENANCE.md).

**Comment by joshtriplett** [comment]
@Byron Owner invitation sent. Teams repo doesn't automatically manage that yet.

**Comment by Byron** [comment]
Thanks a lot! That worked and allowed me to [finish the release](https://github.com/rust-lang/flate2-rs/releases/tag/1.0.27) :).

**Pull request merged**
